### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character... in unicode folder

### ISSUE THREAD

**Issue by hroncok** [pyvec/arca#60]
My PWD is `/home/churchyard/ownCloud/Škola/191/naucse.python.cz` - note the **Š**.

I'm checked out at https://github.com/pyvec/naucse.python.cz/pull/555 and I run:

```
NAUCSE_TRUSTED_REPOS='*cvut*' pipenv run naucse serve
```

I open http://0.0.0.0:8003/ and boom:

```
Traceback (most recent call last):
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/naucse/views.py", line 50, in _get_model
    g.model.load_local_courses(load_path)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/naucse/models.py", line 1014, in load_local_courses
    _load_local_course(course_path, slug)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/naucse/models.py", line 989, in _load_local_course
    slug, parent=self, link_info=link_info,
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/naucse/models.py", line 747, in load_remote
    renderer = arca_renderer.Renderer(parent.arca, url, branch)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/naucse/arca_renderer.py", line 30, in __init__
    readme_path = arca.static_filename(url, branch, 'README.md')
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/arca/_arca.py", line 427, in static_filename
    _, repo_path = self.get_files(repo, branch, depth=depth, reference=reference)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/arca/_arca.py", line 328, in get_files
    reference=reference)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/arca/_arca.py", line 291, in _pull
    return Repo.clone_from(repo, str(repo_path), branch=branch, **kwargs)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/git/repo/base.py", line 982, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/git/repo/base.py", line 933, in _clone
    finalize_process(proc, stderr=stderr)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/git/util.py", line 333, in finalize_process
    proc.wait(**kwargs)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/git/cmd.py", line 404, in wait
    stderr = force_bytes(stderr)
  File "/home/churchyard/.local/share/virtualenvs/naucse.python.cz-0tptgw1t/lib/python3.6/site-packages/gitdb/utils/encoding.py", line 16, in force_bytes
    return data.encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0160' in position 40: ordinal not in range(128)
```

**Comment by mikicz** [comment]
Seems like an issue with `gitpython` or its integration. I'll try to replicate, see if a newer version would fix it and if not, try to do a PR with `gitpython`.
